services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: host
    restart: unless-stopped
    
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
      - livekit_data:/data
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
            
  sip:
    image: livekit/sip:latest
    network_mode: host
    volumes:
      - sip_data:/data
    environment:
      SIP_CONFIG_BODY: |
        api_key: 'devkey'
        api_secret: 'secret'
        ws_url: 'ws://localhost:7880'
        redis:
          address: 'localhost:6379'
        sip_port: 5070
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: info
    restart: unless-stopped
    depends_on:
      - redis
      - livekit

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-voice-ai
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  redis_data:
  livekit_data:
  sip_data: